services:

  mongo_arriendos:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_arriendos_data:/data/db
    healthcheck:
      test:
        - CMD
        - mongosh
        - --quiet
        - --eval
        - "db.adminCommand('ping').ok"
      interval: 5s
      timeout: 5s
      retries: 10

  arriendos:
    build:
      context: .
      dockerfile: arriendos/Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo_arriendos:27017
      MONGO_DB: arriendos_db
      ARRIENDOS_API_KEY: ${ARRIENDOS_API_KEY:?Configura ARRIENDOS_API_KEY}
      EQUIPOS_GRPC_ADDRESS: equipos:50051 # Debe coincidir
    depends_on:
      mongo_arriendos:
        condition: service_healthy

volumes:
  mongo_arriendos_data: